# Generated by Django 4.1.1 on 2022-09-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_and_books', '0002_authors_books_authors_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='authors_and_books.books'),
        ),
    ]
